apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: hungtn29
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: sealed-secrets
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 1.16.1 # For helm, this refers to the chart version.
    helm:
      releaseName: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true