# - The cluster generator allows you to generate applications based on the list of clusters defined within ArgoCD
# - The following parameter values to the Application template for each cluster:
#   + name
#   + nameNormalized('name' but normalized to contain only lowercase alphanumeric characers, '-' or '.')
#   + server
#   + metadata.labels.<key> (for each label in the Secret)
#   + metadata.annotations.<key> (for each annotation in the Secret)
# - Additional key/value pairs can be set manually via values field
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators: 
  - cluster: {}
template:
  metadata:
    name: '{{name}}-guestbook'